### ISSUE TITLE
I compiled from sources and gets error

### ISSUE THREAD

**Issue by miuirussia** [CptSpaceToaster/CptsModdingLight#1]
---- Minecraft Crash Report ----
// My bad.

Time: 05.01.14 18:32
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: yamhaven.easycoloredlights.blocks.WhiteColoredLightBlock.addColorLightValue(FFF)Lnet/minecraft/block/Block;
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:523)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.NoSuchMethodError: yamhaven.easycoloredlights.blocks.WhiteColoredLightBlock.addColorLightValue(FFF)Lnet/minecraft/block/Block;
    at yamhaven.easycoloredlights.blocks.WhiteColoredLightBlock.turnLightsOn(WhiteColoredLightBlock.java:28)
    at yamhaven.easycoloredlights.blocks.BlockColoredLight.<init>(BlockColoredLight.java:25)
    at yamhaven.easycoloredlights.blocks.WhiteColoredLightBlock.<init>(WhiteColoredLightBlock.java:15)
    at yamhaven.easycoloredlights.blocks.Blocks.init(Blocks.java:40)
    at yamhaven.easycoloredlights.EasyColoredLights.preInit(EasyColoredLights.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Mac OS X (x86_64) version 10.9.1
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 21314120 bytes (20 MB) / 112672768 bytes (107 MB) up to 129957888 bytes (123 MB)
    JVM Flags: 0 total; 
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 4 mods loaded, 4 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized
    EasyColoredLights{1.6.4} [Easy Colored Lights](colored.zip) Unloaded->Constructed->Errored

**Comment by CptSpaceToaster** [comment]
I am assuming you are NOT running the environment in eclipse, but are rather trying to recompile, and distribute the mod.  Take care, we will finish this process as soon as we can, and will take charge in distributing it ourselves.  If you simply received this error within eclipse upon trying to run the Minecraft instance, then read the second segment.

---

For some reason, you didn't override the block class properly.  Make sure your development environment is only using the modded classes, and not minecraft's default classes.  If you try using the default block class, like your code was doing, you'll throw a "No Such Method Error" as I added some methods that are used.

In addition, the library to edit and modify classes on runtime (ASM) hasn't been completely implemented, and we are waiting on a set of fixes to finish up the project.  Currently, the project should be throwing a null pointer, or a Duplicate Method Name, if packaged up properly, I don't know how you got that with the updated repo...

---

If you are receiving this error inside of your MCP workspace, delete the following classes from your MCP workspace in the Minecraft source.  These classes are duplicates and come with the Repo on this page.  You cannot use the default minecraft classes, as I have put considerable time into adding methods and editing them to work with colored light components.

src\minecraft\net\minecraft\block\Block.java
src\minecraft\net\minecraft\block\BlockFire.java
src\minecraft\net\minecraft\block\BlockFlowing.java
src\minecraft\net\minecraft\block\BlockRedstoneRepeater.java
src\minecraft\net\minecraft\block\BlockStationary.java
src\minecraft\net\minecraft\block\BlockTorch.java
src\minecraft\net\minecraft\block\BlockRedstoneTorch.java

src\minecraft\net\minecraft\client\renderer\RenderBlocks.java
src\minecraft\net\minecraft\client\renderer\Tessellator.java

src\minecraft\net\minecraft\world\World.java
src\minecraft\net\minecraft\world\ChunkCache.java

src\minecraft\net\minecraft\world\chunk\storage\ExtendedBlockStorage.java

All of these classes should come with the repo in CptsModdedLight/net/minecraft/*
